### ISSUE TITLE
Brainstorm Design of Camera Holder/Mount 

### ISSUE THREAD

**Issue by jwwangrich** [Duke-BME-Design/CarpalDiem#64]

**Comment by mpm55** [comment]
Notes can be found here 
https://duke.app.box.com/services/box_for_office_online/4881/399738953914/7e6abb.674484a69a76358e02f98f39369b49305ee9bccd881dcc25f0276dddd09bb4d3?node_type=file

**Comment by mpm55** [comment]
Notes can be found here. Ignore previous link.
https://duke.app.box.com/file/399738953914
