### ISSUE TITLE
Purchase Ring Light and Light Reflectors

### ISSUE THREAD

**Issue by tkt8** [Duke-BME-Design/CarpalDiem#68]

**Comment by mpm55** [comment]
Posted the information for both items on the class purchasing excel document so that they can be purchased.

**Comment by mpm55** [comment]
https://duke.app.box.com/file/380795866441

**Comment by tkt8** [comment]
Ring Light Delivered

**Comment by tkt8** [comment]
Waiting for Reflector

**Comment by mpm55** [comment]
Reflector delivered
