### ISSUE TITLE
Take images of hand at various light heights, light/reflector distances, reflector types and box heights 

### ISSUE THREAD

**Issue by mpm55** [Duke-BME-Design/CarpalDiem#90]

**Comment by tkt8** [comment]
Blocked due to Issue #68

**Comment by mpm55** [comment]
Satisfied from issue #91. We did not take images. Instead, we continually moved the camera and lights around in multiple positions until any hand size would be in view and the light would not be in the picture while also providing the best lighting to show all angles.
